# Generated by Django 3.2.6 on 2021-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210816_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(max_length=123),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(max_length=123),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(max_length=123),
        ),
    ]
