# Generated by Django 3.2.6 on 2021-08-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210816_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
