# Generated by Django 3.2.6 on 2021-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210816_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=123),
        ),
    ]
